INSERT INTO `sc_tb_menu` (`id`, `pai`, `nome`, `icone`, `tipo`, `local`, `arquivo`, `url`, `target`, `ativo`, `modulo`, `ordem`, `ad_a_click`, `ad_p_nome`, `ad_p_nome_cor`, `cor_nome`, `cor_icone`, `temp`) VALUES
('maps_01', '000', 'Mapeamentos', 'command', 'N', '.content-body', NULL, '#', NULL, 1, 'maps', 0, NULL, NULL, 'bg-primary', NULL, NULL, NULL),
('maps_02', 'maps_01', 'Configuração', 'settings', 'C', '.content-body', 'mod/maps/frm_cf.php', '#', NULL, 1, 'maps', 0, NULL, NULL, 'bg-primary', NULL, NULL, NULL),
('maps_03', 'maps_01', 'Visitas', 'monitor', 'C', '.content-body', 'mod/maps/visitas.php', '#', NULL, 1, 'maps', 0, 'SlickLoader.enable();', NULL, 'bg-primary', NULL, NULL, NULL),
('maps_04', 'maps_01', 'Microáreas (áreas)', 'monitor', 'C', '.content-body', 'mod/maps/mas.php', '#', NULL, 1, 'maps', 0, NULL, NULL, 'bg-primary', NULL, NULL, NULL),
('maps_05', 'maps_01', 'Focos', 'monitor', 'C', '.content-body', 'mod/maps/focos.php', '#', NULL, 1, 'maps', 0, NULL, NULL, 'bg-primary', NULL, NULL, NULL),
('maps_06', 'maps_01', 'Acompanhamento', 'monitor', 'C', '.content-body', 'mod/maps/acomp.php', '#', NULL, 1, 'maps', 0, NULL, NULL, 'bg-primary', NULL, NULL, NULL),
('maps_07', 'maps_01', 'Acompanhamento (PrevBra)', 'monitor', 'C', '.content-body', 'mod/maps/acomppb.php', '#', NULL, 1, 'maps', 0, NULL, NULL, 'bg-primary', NULL, NULL, NULL);

INSERT INTO `sc_tb_modulos` (`modulo`) VALUES ('maps');


CREATE TABLE IF NOT EXISTS `maps_tb_cf_geral` (
  `id` varchar(11) NOT NULL,
  `ibge` varchar(7) NOT NULL,
  `largura` varchar(20) DEFAULT '1200px',
  `altura` varchar(20) DEFAULT '800px',
  `latitude` DOUBLE NOT NULL DEFAULT -26.741530,
  `longitude` DOUBLE NOT NULL DEFAULT -49.175339,
  `zoom` int(11) NOT NULL DEFAULT 13,
  `tbtmp` int(11) NOT NULL DEFAULT 0,
  `coorintma` int(11) NOT NULL DEFAULT 0,
  `coorintvis` int(11) NOT NULL DEFAULT 0,
  `coorintacomp` int(11) NOT NULL DEFAULT 0,
  `masc` varchar(250) DEFAULT NULL,
  `key_api_bing` varchar(250) DEFAULT NULL,
  `metodo` int(11) NOT NULL DEFAULT 1,
  `maps_nt` int(11) NOT NULL DEFAULT 0,
  CONSTRAINT pk_CE primary key(id,ibge)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `maps_tb_focos` (
  `idg` int(11) NOT NULL AUTO_INCREMENT,
  `id` varchar(11) NOT NULL,
  `ibge` varchar(7) NOT NULL,
  `latitude` DOUBLE NOT NULL DEFAULT 0,
  `longitude` DOUBLE NOT NULL DEFAULT 0,
  `nome` varchar(20) DEFAULT NULL,
  `icone` varchar(100) DEFAULT 'casa1.png',
  `cor_borda` varchar(50) DEFAULT 'red',
  `cor_fundo` varchar(50) DEFAULT '#f03',
  `opacidade` FLOAT NOT NULL DEFAULT 0.5,
  `raio` int(11) NOT NULL DEFAULT 300,
  `descricao` varchar(250) DEFAULT 'txt',
  `ativo` int(11) NOT NULL DEFAULT 1,
  primary key(idg)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `maps_tb_areas` (
  `idg` int(11) NOT NULL AUTO_INCREMENT,
  `id` varchar(11) NOT NULL,
  `ibge` varchar(7) NOT NULL,
  `klink` VARCHAR(60) NOT NULL,
  `nome` varchar(20) DEFAULT NULL,
  `icone` varchar(100) DEFAULT 'casa1.png',
  `cor_borda` varchar(50) DEFAULT 'red',
  `cor_fundo` varchar(50) DEFAULT '#f03',
  `opacidade` FLOAT NOT NULL DEFAULT 0.5,
  `descricao` varchar(250) DEFAULT 'txt',
  `ativo` int(11) NOT NULL DEFAULT 1,
  `ma` varchar(10) NULL,
  primary key(idg)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `maps_tb_areas_pontos` (
  `idg` int(11) NOT NULL AUTO_INCREMENT,
  `id` varchar(11) NOT NULL,
  `ibge` varchar(7) NOT NULL,
  `klink` VARCHAR(60) NOT NULL,
  `latitude` DOUBLE NOT NULL DEFAULT 0,
  `longitude` DOUBLE NOT NULL DEFAULT 0,
  `descricao` varchar(250) DEFAULT 'txt',
  primary key(idg)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `maps_tb_tmp_casas` (
  `idg` int(11) NOT NULL AUTO_INCREMENT,
  `id` varchar(11) NOT NULL,
  `ibge` varchar(7) NOT NULL,
  `datetmp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `co_seq_fat_cad_domiciliar` int(11) NOT NULL DEFAULT 0,
  `co_seq_fat_cad_dom_familia` int(11) NOT NULL DEFAULT 0,
  `co_seq_familia` int(11) NOT NULL DEFAULT 0,
  `co_seq_cds_domicilio` int(11) NOT NULL DEFAULT 0,
  `co_fat_cidadao_pec` int(11) NOT NULL DEFAULT 0,
  `co_unico_domicilio` varchar(250) DEFAULT NULL,
  `nu_latitude` FLOAT NOT NULL DEFAULT 0,
  `nu_longitude` FLOAT NOT NULL DEFAULT 0,
  `nu_cns_responsavel` varchar(15) DEFAULT NULL,
  `nu_cpf_responsavel` varchar(11) DEFAULT NULL,
  `dt_nascimento` varchar(10) DEFAULT NULL,
  `st_recusa_cadastro` int(11) NULL DEFAULT 0,
  `nu_cnes_principal` varchar(15) DEFAULT NULL,
  `nu_cnes` varchar(15) DEFAULT NULL,
  `no_unidade_saude` varchar(250) DEFAULT NULL,
  `unid_saude_no_bairro` varchar(150) DEFAULT NULL,
  `nu_ine_principal` varchar(15) DEFAULT NULL,
  `nu_ine` varchar(15) DEFAULT NULL,
  `no_equipe` varchar(150) DEFAULT NULL,
  `nu_micro_area` varchar(5) DEFAULT NULL,
  `co_dim_tempo` varchar(10) DEFAULT NULL,
  `st_mudou` int(11) NULL DEFAULT 0,
  `dt_inicio_residencia` varchar(10) DEFAULT NULL,
  `st_domicilio_ativo` int(11) NULL DEFAULT 1,
  `qt_morador` int(11) NULL DEFAULT 0,
  `ds_complemento` varchar(150) DEFAULT NULL,
  `no_logradouro` varchar(250) DEFAULT NULL,
  `no_bairro` varchar(150) DEFAULT NULL,
  `ds_cep` varchar(9) DEFAULT NULL,
  `nu_fone_referencia` varchar(20) DEFAULT NULL,
  `nu_fone_residencia` varchar(20) DEFAULT NULL,
  `nu_domicilio` varchar(15) DEFAULT NULL,
  `st_fora_area` int(11) NULL DEFAULT 0,
  `ds_ponto_referencia` varchar(150) DEFAULT NULL,
  `prof_nu_cns` varchar(15) DEFAULT NULL,
  `prof_no_profissional` varchar(150) DEFAULT NULL,
  `nu_cbo` varchar(7) DEFAULT NULL,
  `no_cbo` varchar(250) DEFAULT NULL,
  `no_tipo_logradouro` varchar(50) DEFAULT NULL,
  `no_uf` varchar(150) DEFAULT NULL,
  `sg_uf` varchar(2) DEFAULT NULL,
  `no_municipio` varchar(150) DEFAULT NULL,
  `co_ibge` varchar(7) DEFAULT NULL,
  `mapa_id_area` varchar(50) DEFAULT NULL,
  `mapa_id_osm` varchar(50) DEFAULT NULL,
  `mapa_classe` varchar(20) DEFAULT NULL,
  `mapa_tipo` varchar(20) DEFAULT NULL,
  `mapa_completo` varchar(3000) DEFAULT NULL,
  `mapa_area` varchar(3000) DEFAULT NULL,
  `pg_internet` int(11) NULL DEFAULT 0,
  `nome` varchar(150) DEFAULT NULL,
  `mae` varchar(150) DEFAULT NULL,
   primary key(idg)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
