INSERT INTO `sc_tb_usuarios_perfil` (`id`, `nome`) VALUES
('user', 'Usuário');

INSERT INTO `sc_rl_menu_perfil` (`id_menu`, `id_perfil`) VALUES
('prevbra_01', 'user'),
('prevbra_01', 'user'),
('001', 'user'),
('008', 'user'),
('008', 'user'),
('005', 'user'),
('002', 'user'),
('cidadao_02', 'user'),
('cidadao_02', 'user'),
('cidadao_01', 'user'),
('cidadao_03', 'user'),
('cidadao_03', 'user'),
('cidadao_01', 'user'),
('prevbra_03', 'user'),
('prevbra_03', 'user'),
('prevbra_02', 'user'),
('prevbra_04', 'user'),
('prevbra_04', 'user'),
('prevbra_02', 'user'),
('prevbra_05', 'user'),
('prevbra_05', 'user'),
('prevbra_02', 'user'),
('prevbra_06', 'user'),
('prevbra_06', 'user'),
('prevbra_02', 'user'),
('prevbra_07', 'user'),
('prevbra_07', 'user'),
('prevbra_02', 'user');